/**
 * AUTO-GENERATED Supabase Database Types
 *
 * This file is auto-generated by the Supabase CLI via:
 *   npm run db:generate-types
 *
 * Do not manually edit this file. Re-run the command above after
 * any migration changes to keep types in sync with the database schema.
 *
 * SCHEMA ALIGNMENT: Verified against migrations 001-014 on 2026-02-09.
 */

// ---------------------------------------------------------------------------
// Enums (match SQL CHECK constraints exactly)
// ---------------------------------------------------------------------------

export type OpportunityStage =
  | "discovered"
  | "proposal_sent"
  | "interview"
  | "contracted"
  | "in_progress"
  | "delivered"
  | "review_requested"
  | "complete"
  | "lost"

export type GigStatus = "draft" | "active" | "paused" | "archived"

export type ProjectStatus = "active" | "paused" | "completed" | "cancelled"

export type PlatformStatus =
  | "setup_needed"
  | "application_pending"
  | "active"
  | "paused"
  | "planned"

export type ContractType = "fixed" | "hourly"

export type RevenueEntryType = "gig_payment" | "retainer" | "bonus" | "tip"

// Matches migration 010: CHECK (category IN ('bio','credential','process','testimonial','case_study'))
export type ContentBlockCategory =
  | "bio"
  | "credential"
  | "process"
  | "testimonial"
  | "case_study"

// ---------------------------------------------------------------------------
// Row types — one per database table, matching SQL migrations exactly
// ---------------------------------------------------------------------------

/** Migration 001 */
export interface Platform {
  id: string
  name: string
  profile_url: string
  profile_status: PlatformStatus
  headline: string
  overview_text: string
  hourly_rate: number | null
  skills_tags: string[]
  specialized_profiles_json: Record<string, unknown>[]
  created_at: string
  updated_at: string
}

/** Migration 002 */
export interface ServicePillar {
  id: string
  name: string
  description: string
  color: string
  sort_order: number
  created_at: string
  updated_at: string
}

/** Migration 003 */
export interface GigListing {
  id: string
  platform_id: string
  pillar_id: string
  title: string
  description: string
  tags: string[]
  status: GigStatus
  pricing_basic: number | null
  pricing_standard: number | null
  pricing_premium: number | null
  delivery_days_basic: number | null
  delivery_days_standard: number | null
  delivery_days_premium: number | null
  gig_url: string
  impressions: number
  clicks: number
  orders: number
  conversion_rate: number
  revenue_total: number
  created_at: string
  updated_at: string
}

/** Migration 011 — uses JSONB for pricing and performance snapshots */
export interface GigVersion {
  id: string
  gig_id: string
  version_number: number
  title: string
  description: string
  tags: string[]
  pricing_json: Record<string, unknown>
  change_notes: string
  performance_snapshot_json: Record<string, unknown>
  created_at: string
}

/** Migration 004 */
export interface Opportunity {
  id: string
  platform_id: string
  pillar_id: string | null
  gig_id: string | null
  stage: OpportunityStage
  job_title: string
  job_url: string
  job_description: string
  client_name: string
  client_company: string
  client_location: string
  budget_min: number | null
  budget_max: number | null
  contract_type: ContractType
  proposal_text: string
  proposal_template_id: string | null
  proposal_sent_at: string | null
  response_received_at: string | null
  contracted_at: string | null
  contract_value: number | null
  estimated_hours: number | null
  actual_hours: number | null
  delivery_deadline: string | null
  delivered_at: string | null
  review_requested_at: string | null
  review_received_at: string | null
  review_rating: number | null
  review_text: string
  notes: string
  created_at: string
  updated_at: string
}

/** Migration 005 — win_rate is a GENERATED column */
export interface ProposalTemplate {
  id: string
  name: string
  pillar_id: string | null
  platform_id: string | null
  template_text: string
  variables: string[]
  times_used: number
  times_won: number
  win_rate: number // GENERATED ALWAYS AS (times_won / times_used)
  tags: string[]
  created_at: string
  updated_at: string
}

/** Migration 006 */
export interface Project {
  id: string
  opportunity_id: string | null
  title: string
  status: ProjectStatus
  start_date: string | null
  target_delivery_date: string | null
  actual_delivery_date: string | null
  milestones_json: Record<string, unknown>[]
  checklist_json: Record<string, unknown>[]
  time_entries_json: Record<string, unknown>[]
  client_communication_log_json: Record<string, unknown>[]
  created_at: string
  updated_at: string
}

/** Migration 007 */
export interface PortfolioItem {
  id: string
  pillar_id: string | null
  title: string
  client_name: string
  problem_description: string
  solution_description: string
  results_description: string
  metrics_json: Record<string, unknown>
  images: string[]
  platforms_used_on: string[]
  is_public: boolean
  created_at: string
  updated_at: string
}

/** Migration 008 — net_amount is a GENERATED column */
export interface RevenueEntry {
  id: string
  opportunity_id: string | null
  platform_id: string | null
  pillar_id: string | null
  amount: number
  currency: string
  entry_type: RevenueEntryType
  received_date: string
  platform_fee_amount: number
  net_amount: number // GENERATED ALWAYS AS (amount - platform_fee_amount)
  notes: string
  created_at: string
}

/**
 * Migration 009 — matches SQL exactly:
 * proposals_sent, proposals_viewed, responses_received, contracts_won,
 * gig_impressions, gig_clicks, gig_orders, revenue, notes
 * Note: no updated_at column in this table, UNIQUE(date, platform_id)
 */
export interface DailyMetrics {
  id: string
  date: string
  platform_id: string | null
  proposals_sent: number
  proposals_viewed: number
  responses_received: number
  contracts_won: number
  gig_impressions: number
  gig_clicks: number
  gig_orders: number
  revenue: number
  notes: string
  created_at: string
}

/**
 * Migration 010 — matches SQL exactly:
 * category CHECK ('bio','credential','process','testimonial','case_study'),
 * content_text (not 'body'), platform_tags/pillar_tags (TEXT[] not FKs),
 * times_used (not is_active)
 */
export interface ContentBlock {
  id: string
  category: ContentBlockCategory
  title: string
  content_text: string
  platform_tags: string[]
  pillar_tags: string[]
  times_used: number
  created_at: string
  updated_at: string
}

// ---------------------------------------------------------------------------
// Typed JSON structures for JSONB columns
// ---------------------------------------------------------------------------

export interface Milestone {
  id: string
  title: string
  description?: string
  due_date?: string
  completed: boolean
  completed_at?: string
}

export interface ChecklistItem {
  id: string
  text: string
  completed: boolean
  completed_at?: string
}

export interface TimeEntry {
  id: string
  date: string
  hours: number
  description: string
}

export interface CommunicationLog {
  id: string
  date: string
  channel: "email" | "slack" | "call" | "platform_message" | "other"
  summary: string
}

export interface GigPricing {
  basic: { price: number; delivery_days: number; description?: string }
  standard: { price: number; delivery_days: number; description?: string }
  premium: { price: number; delivery_days: number; description?: string }
}

export interface PerformanceSnapshot {
  impressions: number
  clicks: number
  orders: number
  conversion_rate: number
  revenue_total: number
  captured_at: string
}

// ---------------------------------------------------------------------------
// Utility types
// ---------------------------------------------------------------------------

type Tables = Database["public"]["Tables"]

/** Extract the Row type for a given table name */
export type TableRow<T extends keyof Tables> = Tables[T]["Row"]

/** Extract the Insert type for a given table name */
export type TableInsert<T extends keyof Tables> = Tables[T]["Insert"]

/** Extract the Update type for a given table name */
export type TableUpdate<T extends keyof Tables> = Tables[T]["Update"]

/** Opportunity with joined platform and pillar data */
export interface OpportunityWithRelations extends Opportunity {
  platforms?: Pick<Platform, "name"> | null
  service_pillars?: Pick<ServicePillar, "name" | "color"> | null
  proposal_templates?: Pick<ProposalTemplate, "name"> | null
}

/** Gig listing with joined platform and pillar data */
export interface GigListingWithRelations extends GigListing {
  platforms?: Pick<Platform, "name"> | null
  service_pillars?: Pick<ServicePillar, "name" | "color"> | null
}

/** Revenue entry with joined platform and pillar data */
export interface RevenueEntryWithRelations extends RevenueEntry {
  platforms?: Pick<Platform, "name"> | null
  service_pillars?: Pick<ServicePillar, "name" | "color"> | null
}

// ---------------------------------------------------------------------------
// Database schema definition
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      platforms: {
        Row: Platform
        Insert: Partial<Platform> & Pick<Platform, "name">
        Update: Partial<Platform>
      }
      service_pillars: {
        Row: ServicePillar
        Insert: Partial<ServicePillar> & Pick<ServicePillar, "name" | "color">
        Update: Partial<ServicePillar>
      }
      gig_listings: {
        Row: GigListing
        Insert: Partial<GigListing> &
          Pick<GigListing, "platform_id" | "pillar_id" | "title">
        Update: Partial<GigListing>
      }
      gig_versions: {
        Row: GigVersion
        Insert: Partial<GigVersion> &
          Pick<GigVersion, "gig_id" | "version_number" | "title">
        Update: Partial<GigVersion>
      }
      opportunities: {
        Row: Opportunity
        Insert: Partial<Opportunity> &
          Pick<Opportunity, "platform_id" | "job_title">
        Update: Partial<Opportunity>
      }
      proposal_templates: {
        Row: ProposalTemplate
        Insert: Partial<ProposalTemplate> & Pick<ProposalTemplate, "name">
        Update: Partial<ProposalTemplate>
      }
      projects: {
        Row: Project
        Insert: Partial<Project> & Pick<Project, "title">
        Update: Partial<Project>
      }
      portfolio_items: {
        Row: PortfolioItem
        Insert: Partial<PortfolioItem> & Pick<PortfolioItem, "title">
        Update: Partial<PortfolioItem>
      }
      revenue_entries: {
        Row: RevenueEntry
        Insert: Partial<RevenueEntry> &
          Pick<RevenueEntry, "amount" | "received_date">
        Update: Partial<RevenueEntry>
      }
      daily_metrics: {
        Row: DailyMetrics
        Insert: Partial<DailyMetrics> & Pick<DailyMetrics, "date">
        Update: Partial<DailyMetrics>
      }
      content_blocks: {
        Row: ContentBlock
        Insert: Partial<ContentBlock> &
          Pick<ContentBlock, "category" | "title" | "content_text">
        Update: Partial<ContentBlock>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      opportunity_stage: OpportunityStage
      gig_status: GigStatus
      project_status: ProjectStatus
      platform_status: PlatformStatus
      contract_type: ContractType
      revenue_entry_type: RevenueEntryType
      content_block_category: ContentBlockCategory
    }
  }
}
