/**
 * AUTO-GENERATED Supabase Database Types
 *
 * This file is auto-generated by the Supabase CLI via:
 *   npm run db:generate-types
 *
 * Do not manually edit this file. Re-run the command above after
 * any migration changes to keep types in sync with the database schema.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type OpportunityStage =
  | "discovered"
  | "proposal_sent"
  | "interview"
  | "contracted"
  | "in_progress"
  | "delivered"
  | "review_requested"
  | "complete"
  | "lost"

export type GigStatus = "draft" | "active" | "paused" | "archived"

export type ProjectStatus = "active" | "paused" | "completed" | "cancelled"

export type PlatformStatus =
  | "setup_needed"
  | "application_pending"
  | "active"
  | "paused"
  | "planned"

export type ContractType = "fixed" | "hourly"

export type RevenueEntryType = "gig_payment" | "retainer" | "bonus" | "tip"

export type ContentBlockCategory =
  | "headline"
  | "overview"
  | "case_study"
  | "faq"
  | "skill_description"
  | "testimonial"

// ---------------------------------------------------------------------------
// Row types — one per database table
// ---------------------------------------------------------------------------

export interface Platform {
  id: string
  name: string
  profile_url: string
  profile_status: PlatformStatus
  headline: string
  overview_text: string
  hourly_rate: number | null
  skills_tags: string[]
  specialized_profiles_json: Record<string, unknown>[]
  created_at: string
  updated_at: string
}

export interface ServicePillar {
  id: string
  name: string
  description: string
  color: string
  sort_order: number
  created_at: string
  updated_at: string
}

export interface GigListing {
  id: string
  platform_id: string
  pillar_id: string
  title: string
  description: string
  tags: string[]
  status: GigStatus
  pricing_basic: number | null
  pricing_standard: number | null
  pricing_premium: number | null
  delivery_days_basic: number | null
  delivery_days_standard: number | null
  delivery_days_premium: number | null
  gig_url: string
  impressions: number
  clicks: number
  orders: number
  conversion_rate: number
  revenue_total: number
  created_at: string
  updated_at: string
}

export interface GigVersion {
  id: string
  gig_id: string
  version_number: number
  title: string
  description: string
  tags: string[]
  pricing_basic: number | null
  pricing_standard: number | null
  pricing_premium: number | null
  delivery_days_basic: number | null
  delivery_days_standard: number | null
  delivery_days_premium: number | null
  change_notes: string
  created_at: string
}

export interface Opportunity {
  id: string
  platform_id: string
  pillar_id: string | null
  gig_id: string | null
  stage: OpportunityStage
  job_title: string
  job_url: string
  job_description: string
  client_name: string
  client_company: string
  client_location: string
  budget_min: number | null
  budget_max: number | null
  contract_type: ContractType
  proposal_text: string
  proposal_template_id: string | null
  proposal_sent_at: string | null
  response_received_at: string | null
  contracted_at: string | null
  contract_value: number | null
  estimated_hours: number | null
  actual_hours: number | null
  delivery_deadline: string | null
  delivered_at: string | null
  review_requested_at: string | null
  review_received_at: string | null
  review_rating: number | null
  review_text: string
  notes: string
  created_at: string
  updated_at: string
}

export interface ProposalTemplate {
  id: string
  name: string
  pillar_id: string | null
  platform_id: string | null
  template_text: string
  variables: string[]
  times_used: number
  times_won: number
  win_rate: number
  tags: string[]
  created_at: string
  updated_at: string
}

export interface Project {
  id: string
  opportunity_id: string | null
  title: string
  status: ProjectStatus
  start_date: string | null
  target_delivery_date: string | null
  actual_delivery_date: string | null
  milestones_json: Record<string, unknown>[]
  checklist_json: Record<string, unknown>[]
  time_entries_json: Record<string, unknown>[]
  client_communication_log_json: Record<string, unknown>[]
  created_at: string
  updated_at: string
}

export interface PortfolioItem {
  id: string
  pillar_id: string | null
  title: string
  client_name: string
  problem_description: string
  solution_description: string
  results_description: string
  metrics_json: Record<string, unknown>
  images: string[]
  platforms_used_on: string[]
  is_public: boolean
  created_at: string
  updated_at: string
}

export interface RevenueEntry {
  id: string
  opportunity_id: string | null
  platform_id: string | null
  pillar_id: string | null
  amount: number
  currency: string
  entry_type: RevenueEntryType
  received_date: string
  platform_fee_amount: number
  net_amount: number
  notes: string
  created_at: string
}

export interface DailyMetrics {
  id: string
  date: string
  platform_id: string | null
  proposals_sent: number
  proposals_won: number
  impressions: number
  clicks: number
  orders: number
  revenue: number
  hours_worked: number
  notes: string
  created_at: string
  updated_at: string
}

export interface ContentBlock {
  id: string
  pillar_id: string | null
  platform_id: string | null
  category: ContentBlockCategory
  title: string
  body: string
  tags: string[]
  is_active: boolean
  created_at: string
  updated_at: string
}

// ---------------------------------------------------------------------------
// Database schema definition
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      platforms: {
        Row: Platform
        Insert: Partial<Platform> & Pick<Platform, "name">
        Update: Partial<Platform>
      }
      service_pillars: {
        Row: ServicePillar
        Insert: Partial<ServicePillar> & Pick<ServicePillar, "name" | "color">
        Update: Partial<ServicePillar>
      }
      gig_listings: {
        Row: GigListing
        Insert: Partial<GigListing> &
          Pick<GigListing, "platform_id" | "pillar_id" | "title">
        Update: Partial<GigListing>
      }
      gig_versions: {
        Row: GigVersion
        Insert: Partial<GigVersion> &
          Pick<GigVersion, "gig_id" | "version_number" | "title">
        Update: Partial<GigVersion>
      }
      opportunities: {
        Row: Opportunity
        Insert: Partial<Opportunity> &
          Pick<Opportunity, "platform_id" | "job_title">
        Update: Partial<Opportunity>
      }
      proposal_templates: {
        Row: ProposalTemplate
        Insert: Partial<ProposalTemplate> & Pick<ProposalTemplate, "name">
        Update: Partial<ProposalTemplate>
      }
      projects: {
        Row: Project
        Insert: Partial<Project> & Pick<Project, "title">
        Update: Partial<Project>
      }
      portfolio_items: {
        Row: PortfolioItem
        Insert: Partial<PortfolioItem> & Pick<PortfolioItem, "title">
        Update: Partial<PortfolioItem>
      }
      revenue_entries: {
        Row: RevenueEntry
        Insert: Partial<RevenueEntry> &
          Pick<RevenueEntry, "amount" | "received_date">
        Update: Partial<RevenueEntry>
      }
      daily_metrics: {
        Row: DailyMetrics
        Insert: Partial<DailyMetrics> & Pick<DailyMetrics, "date">
        Update: Partial<DailyMetrics>
      }
      content_blocks: {
        Row: ContentBlock
        Insert: Partial<ContentBlock> &
          Pick<ContentBlock, "category" | "title" | "body">
        Update: Partial<ContentBlock>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      opportunity_stage: OpportunityStage
      gig_status: GigStatus
      project_status: ProjectStatus
      platform_status: PlatformStatus
      contract_type: ContractType
      revenue_entry_type: RevenueEntryType
      content_block_category: ContentBlockCategory
    }
  }
}
